FROM node:18-alpine

WORKDIR /app
COPY . .

ARG UNAME=jenkins
ARG UID=1000
ARG GID=1000

RUN addgroup --gid $GID $UNAME && adduser -D --uid $UID $UNAME -G $UNAME  && chown -R $UID:$GID /app

USER $UNAME

CMD ["sh", "bin/build.sh"]
